services:
  postgres:
    image: postgres:16-alpine
    container_name: jubel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tasbdkel5
      POSTGRES_DB: jubel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - jubel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jubel_backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=tasbdkel5
      - DB_NAME=jubel_db
      - JWT_SECRET=kelompok5tasbd
      - APP_PORT=8080
      - UPLOAD_DIR=/app/uploads
      - MAX_UPLOAD_SIZE=5242880
    volumes:
      - ./uploads:/app/uploads
    restart: always
    networks:
      - jubel-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`besbd.fuadfakhruz.id`)
      - traefik.http.routers.backend.entrypoints=web,websecure
      - traefik.http.services.backend.loadbalancer.server.port=8080
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=myresolver

networks:
  jubel-network:
    driver: bridge

volumes:
  postgres_data:
